title: Use the Pico LED for debugging
hero_image: images/banner.png
description: pico-debug-led description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
